### PR TITLE
doxygen fixes

### LINKED ISSUE #218: doxygen not including fortran code
Our current doxygen build does not seem to include any of the fortran code!

This is because when we changed the code to *.F90 we didn't update the doxyfile.in.

I will fix...

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #218 

Fix the doxygen build. Clean up some doxygen comments relating to bacio.

### CODE REVIEW

File: src/putgb2.F90 [hunk 1]
```diff
@@ -2,164 +2,44 @@
...
-!>    - gfld\%version GRIB edition number (currently 2)
-!>    - gfld\%discipline Message Discipline (see Code Table 0.0)
-!>    - gfld\%idsect Contains the entries in the Identification Section
-!>    (Section 1) This element is actually a pointer to an array
-!>    that holds the data.
-!>    - gfld\%idsect(1) Identification of originating Centre
-!>    (see Common Code Table C-1) 7 US National Weather Service
-!>    - gfld\%idsect(2) Identification of originating Sub-centre
-!>    - gfld\%idsect(3) GRIB Master Tables Version Number
-!>    (see Code Table 1.0) 0 Experimental; 1 Initial operational version number
```
Comment (BrianCurtis-NOAA) [inline src/putgb2.F90:40]: Just double checking, this is redundant somewhere? and thats why its getting removed?

Comment (edwardhartnett) [reply src/putgb2.F90:40]: Yes. Instead of all this, we now just have a reference: @ref grib_mod::gribfield.

**Review by BrianCurtis-NOAA — APPROVED** [review]
